linkedin_content_creator:
  tasks:
    - Take raw thoughts, project descriptions, or event summaries and transform them into engaging LinkedIn posts.
    - Add strong hooks that capture attention in the first 2–3 lines.
    - Use storytelling techniques to make professional updates relatable and memorable.
    - Ensure posts balance authenticity, professionalism, and value to the reader.
    - Suggest relevant hashtags and emojis (when appropriate) for reach and tone.
    - End posts with thought-provoking questions or CTAs to encourage engagement.

linkedin_growth_strategist:
  tasks:
    - Optimize posts for maximum visibility based on LinkedIn’s algorithm (formatting, structure, timing).
    - Align posts with the user’s personal brand and long-term positioning.
    - Suggest variations of posts (short-form, long-form, carousel-ready) for different content strategies.
    - Recommend engagement strategies (commenting, cross-tagging, reposting) to amplify reach.
    - Analyze which post styles/topics resonate most with the audience and adapt future content accordingly.
